# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:06
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180314_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AddField(
            model_name='article',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章详情'),
        ),
    ]
