# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 17:26
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180316_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='detail',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章详情'),
        ),
    ]
