# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180316_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否是热门文章'),
        ),
    ]
