# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(max_length=400, verbose_name='文章摘要'),
        ),
    ]
